// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS_tSvgR9EyEVqtV6fDWU3K8YugHiFjX4',
    appId: '1:940262216174:web:e1beb9d89bbfaee97dbeff',
    messagingSenderId: '940262216174',
    projectId: 'babyshop-1f281',
    authDomain: 'babyshop-1f281.firebaseapp.com',
    databaseURL: 'https://babyshop-1f281-default-rtdb.firebaseio.com',
    storageBucket: 'babyshop-1f281.firebasestorage.app',
    measurementId: 'G-1ZFLSQQN27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2xopOmYXEmEgLO_otXvcDUyZ8nGJWo7o',
    appId: '1:940262216174:android:76e66df2220e759c7dbeff',
    messagingSenderId: '940262216174',
    projectId: 'babyshop-1f281',
    databaseURL: 'https://babyshop-1f281-default-rtdb.firebaseio.com',
    storageBucket: 'babyshop-1f281.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6c4yh--GFe1FcwohSzPiHo9UVtuNhs6I',
    appId: '1:940262216174:ios:ef2b9cac5b5748437dbeff',
    messagingSenderId: '940262216174',
    projectId: 'babyshop-1f281',
    databaseURL: 'https://babyshop-1f281-default-rtdb.firebaseio.com',
    storageBucket: 'babyshop-1f281.firebasestorage.app',
    iosBundleId: 'com.example.babyshophub',
  );

}